services:
  host:
    container_name: host
    tty: true
    image: nsbyteone/awesomectf-host_arm:latest
    ports:
      - "22:22"
      - "13371:13371"

  mysql:
    container_name: mysql
    image: nsbyteone/awesomectf-mysql_arm:latest
    ports:
      - "3306:3306"
